server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms_generalsetup
    username: root
    password: vishal
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
